# Generated by Django 4.2.7 on 2023-12-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
