# Generated by Django 4.2.7 on 2023-12-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_cover_letter_user_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='technology_stacks',
            field=models.ManyToManyField(blank=True, to='user.technologystack'),
        ),
    ]
