# Generated by Django 4.2.7 on 2023-12-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_technologystack_user_technology_stacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
