# Generated by Django 4.2.7 on 2024-01-02 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_crawling'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawling',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested_crawlings', to=settings.AUTH_USER_MODEL),
        ),
    ]
